[project]
name = "rml-shacl"
version = "0.1.0"
description = "SHACL shapes to validate RML mapping rules"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyshacl>=0.30.1",
]

[dependency-groups]
dev = [
    "parameterized>=0.9.0",
]
